schema.ymlversion: 2

models:
  - name: dim_products
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['product_id']
      - positive_price

  - name: fact_orders
    tests:
      - valid_order_status
      - no_future_order_date
      - positive_order_quantity
