version: 2

models:
  - name: dim_customers
    description: "Tabla de clientes limpia y normalizada"
    columns:
      - name: customer_id
        description: "ID único del cliente"
        tests:
          - unique
          - not_null
      - name: email
        description: "Correo electrónico del cliente"
        tests:
          - not_null
      - name: segment
        description: "Segmento del cliente"

  - name: dim_products
    description: "Tabla de productos limpia y normalizada"
    columns:
      - name: product_id
        description: "ID único del producto"
        tests:
          - unique
          - not_null
      - name: price
        description: "Precio del producto"
        tests:
          - not_null
      - name: category
        description: "Categoría del producto"

  - name: fact_orders
    description: "Tabla de hechos combinando órdenes y detalles de órdenes"
    columns:
      - name: order_id
        description: "ID de la orden"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID del cliente"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id
      - name: product_id
        description: "ID del producto"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id
      - name: total_amount
        description: "Monto total calculado de la orden"
        tests:
          - not_null

  - name: fact_web_events
    description: "Tabla de eventos web de los clientes"
    columns:
      - name: session_id
        description: "ID de la sesión"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID del cliente asociado"
        tests:
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id
      - name: event_timestamp
        description: "Momento del evento"
        tests:
          - not_null
      - name: event_type
        description: "Tipo de evento"
        tests:
          - not_null
